### ISSUE TITLE
Getting record key

### ISSUE THREAD

**Issue by mapohjola** [mfeckie/ember-cli-indexeddb-wrapper#1]
Finding records with getAll is not returning the key of the record in the db. You need the key for updating or deleting the record. I suggest changing the array to object that getAll is returning and setting the key as index. This still leaves problems with knowing the record key for getOneByIndex.

**Comment by mfeckie** [comment]
Hey thanks for the feedback.  I have actually stopped developing this adapter because I've found indexeddb to be inconsistently implemented, so it's usefulness was limited for my use case.  If you are keep to use and want to submit a pull request, I'm happy to merge.
